export const SPARK_PLUGIN_PACKAGES = {
  'com.comphenix.protocol': 'ProtocolLib',
  'com.github.retrooper.packetevents': 'packetevents',
  'com.sk89q.worldguard': 'WorldGuard',
  'net.citizensnpcs': 'Citizens',
  'io.lumine.mythic': 'MythicMobs',
  'io.lumine.mythic.bukkit': 'MythicMobs',
  'com.sk89q.worldedit': 'WorldEdit',
  'com.fastasyncworldedit': 'FastAsyncWorldEdit',
  'dev.lone.itemsadder': 'ItemsAdder',
  'com.nisovin.magicspells': 'MagicSpells',
  'com.ticxo.modelengine': 'ModelEngine',
  'me.libraryaddict.disguises': 'LibsDisguises',
  'com.earth2me.essentials': 'Essentials',
  'net.essentialsx': 'Essentials',
  'com.bgsoftware': 'BGSoftware',
  'fr.xephi.authme': 'AuthMe',
  'com.gmail.nossr50': 'mcMMO',
};
